### ISSUE TITLE
有国内安装方式吗？

### ISSUE THREAD

**Issue by hkcyl123** [modernizing/coca#26]
用go install github.com/modernizing/coca@latest 安装 超时了

**Comment by phodal** [comment]
直接 release 里下载 exe 不香？

**Comment by hkcyl123** [comment]
是我傻逼了

**Comment by hkcyl123** [comment]
m1 版本的话，我直接下mac_os 加上 dmg后缀？
我需要怎么做

**Comment by phodal** [comment]
咦，没试过，m1，不确定能不能工作

**Comment by hkcyl123** [comment]
试试啰，我下了mac版本的，但是提示打不开，我需要怎么做呢？

**Comment by phodal** [comment]
mac_os 那个是个 CLI 应用，需要在命令行里执行。我看了网上说要更新 Golang 版本，就可以了

**Comment by hkcyl123** [comment]
具体命令是咋样的。。刚换的电脑，还没摸透

**Comment by phodal** [comment]
CLI 应用。你把 coca_macos 改为 coca，命令见 README.md

**Comment by hkcyl123** [comment]
了解了，谢谢

**Comment by phodal** [comment]
不行的话，可以试一下 2.3.0 版本，使用提 Go 1.18 构建的：https://github.com/modernizing/coca/releases/tag/v2.3.0

**Comment by hkcyl123** [comment]
emmm，这个需要配置环境变量吗？把他放到桌面，然后sudo跑，提示的是command not found

**Comment by phodal** [comment]
直接 `./coca` 就好了

**Comment by hkcyl123** [comment]
![1652413618182](https://user-images.githubusercontent.com/23721760/168207534-20a0016a-dc3e-45bb-98ed-9a38889f45f4.jpg) 现在是这种情况

**Comment by hkcyl123** [comment]
就很尴尬

**Comment by hkcyl123** [comment]
东西我也放在桌面并且改好名字了

**Comment by phodal** [comment]
没有 `chmod +x` 吧

**Comment by hkcyl123** [comment]
好了，谢谢大佬

**Comment by phodal** [comment]
X
